[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

[build]
target = "x86_64-unknown-linux-musl"
rustflags = ["--cfg=has_std", "-Cpanic=abort"]
